# config/play.yaml
defaults:
  - gomoku: 5x5
  - _self_ # Add _self_ for correct composition order (Hydra 1.1+)
  # Add other defaults if necessary, e.g., from ppo if model loading needs it

# Hydra settings
hydra:
  run:
    dir: ./outputs/play/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    name: interactive_play

# Play specific parameters
checkpoint_dir: "artifacts/checkpoints_versus" # Relative path to the DIRECTORY containing steps (e.g., 100, 200)
checkpoint_step: 8000 # Specific step (sub-directory) to load

# Agent configuration
agent_role: white # Which agent to load from the checkpoint ('black' or 'white')

# Gomoku environment settings (inherited from defaults)

# User interaction settings
user_plays: black # Which color the human plays ('black' or 'white')
seed: 42

# Gomoku settings (can be overridden from command line)
# Values from gomoku/5x5.yaml will be used unless specified here or via CLI
# gomoku:
#   board_size: 5
#   win_length: 4 # Assuming 5x5 uses win_length 4, adjust if needed 

# ----- Play Script Specific -----

# Example: How to run
# python src/alphagomoku/scripts/play.py # Uses defaults
# python src/alphagomoku/scripts/play.py agent_role=white user_plays=black checkpoint_step=500
# python src/alphagomoku/scripts/play.py checkpoint_dir=path/to/my/checkpoints 