# @package _global_

defaults:
  - _self_ # Ensures values in this file are loaded
  - gomoku: 5x5 # Correct path to gomoku config group
  - ppo: default
  - override hydra/job_logging: default
  - override hydra/hydra_logging: default

# Overall training configuration
seed: 42

# Training loop parameters
num_envs: 512 # Number of parallel environments
num_epochs: 1000        # Total number of PPO update epochs

# Evaluation parameters
eval_frequency: 50       # Evaluate every N epochs
eval_games: 128          # Number of games to play during evaluation

# Checkpointing parameters
save_frequency: 50       # Save checkpoint every N epochs
checkpoint_dir: "checkpoints" # Relative to Hydra output dir
max_checkpoints: 10

# WandB configuration
wandb:
  project: "alphagomoku-ppo"
  entity: ammar7 # Set your wandb entity here or via env var WANDB_ENTITY
  run_name: null # If None, wandb generates one
  mode: "online" # or "disabled"

# Hydra specific configuration
hydra:
  run:
    dir: ${oc.env:PWD}/artifacts/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${oc.env:PWD}/artifacts/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  output_subdir: .hydra # Disable the .hydra subdirectory

# Miscellaneous
render: false
