_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.12.10
        t:
            "1":
                - 12
                - 45
                - 50
                - 55
            "2":
                - 12
                - 45
                - 50
                - 55
            "3":
                - 16
                - 23
                - 35
                - 55
            "4": 3.12.10
            "5": 0.19.9
            "8":
                - 5
            "10":
                - 20
            "12": 0.19.9
            "13": linux-x86_64
checkpoint_dir:
    value: checkpoints
eval_frequency:
    value: 50
eval_games:
    value: 128
gomoku:
    value:
        board_size: 5
        win_length: 3
max_checkpoints:
    value: 10
num_envs:
    value: 256
num_epochs:
    value: 1000
ppo:
    value:
        clip_eps: 0.2
        entropy_decay_steps: 50000
        gae_lambda: 0.95
        gamma: 0.99
        initial_entropy_coef: 0.1
        learning_rate: 0.0001
        max_grad_norm: 1
        min_entropy_coef: 0.0001
        num_minibatches: 4
        update_epochs: 4
        vf_coef: 0.5
        weight_decay: 0.0001
render:
    value: false
save_frequency:
    value: 50
seed:
    value: 42
wandb:
    value:
        entity: ammar7
        mode: online
        project: alphagomoku-ppo
        run_name: null
